version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: publicast_mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: publicast
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: publicast_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  postgres-helpcenter:
    image: pgvector/pgvector:pg16
    container_name: publicast_postgres_helpcenter
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: publicast_help_center
      POSTGRES_USER: helpcenter_user
      POSTGRES_PASSWORD: helpcenter_password
    volumes:
      - postgres_helpcenter_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  redis_data:
  postgres_helpcenter_data:
