-- AlterTable
ALTER TABLE `posts` MODIFY `status` ENUM('DRAFT', 'SCHEDULED', 'PENDING_APPROVAL', 'APPROVED', 'PUBLISHED', 'PUBLISHING', 'RETRYING', 'FAILED', 'REJECTED', 'PAUSED') NOT NULL DEFAULT 'DRAFT';
