-- AlterTable
ALTER TABLE `templates` ADD COLUMN `format` ENUM('IMAGE', 'VIDEO', 'TEXT', 'CAROUSEL') NULL;
ALTER TABLE `templates` ADD COLUMN `goal` ENUM('ENGAGEMENT', 'BRAND_AWARENESS', 'EDUCATION', 'COMMUNITY', 'SALES') NULL;
