-- AlterTable
ALTER TABLE `teams` MODIFY `role` ENUM('OWNER', 'ADMIN', 'MANAGER', 'STAFF', 'USER', 'EDITOR', 'VIEWER', 'ANALYST', 'STREAM_MANAGER', 'CONTENT_MANAGER', 'CONTENT_CREATOR', 'STREAM_OPERATOR', 'CLIENT') NOT NULL;

-- AlterTable
ALTER TABLE `users` ADD COLUMN `address` VARCHAR(191) NULL,
    ADD COLUMN `bio` TEXT NULL,
    ADD COLUMN `industry` VARCHAR(191) NULL,
    ADD COLUMN `phone` VARCHAR(191) NULL,
    MODIFY `role` ENUM('OWNER', 'ADMIN', 'MANAGER', 'STAFF', 'USER', 'EDITOR', 'VIEWER', 'ANALYST', 'STREAM_MANAGER', 'CONTENT_MANAGER', 'CONTENT_CREATOR', 'STREAM_OPERATOR', 'CLIENT') NOT NULL DEFAULT 'OWNER';
