/*
  Warnings:

  - You are about to drop the column `livestreamId` on the `approval_workflows` table. All the data in the column will be lost.
  - You are about to drop the column `supportsLivestream` on the `youtube_channels` table. All the data in the column will be lost.
  - You are about to drop the `livestream_highlights` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `livestreams` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `post_analytics_daily_snapshot` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE `approval_workflows` DROP FOREIGN KEY `approval_workflows_livestreamId_fkey`;

-- DropForeignKey
ALTER TABLE `livestream_highlights` DROP FOREIGN KEY `livestream_highlights_brandId_fkey`;

-- DropForeignKey
ALTER TABLE `livestreams` DROP FOREIGN KEY `livestreams_brandId_fkey`;

-- DropForeignKey
ALTER TABLE `livestreams` DROP FOREIGN KEY `livestreams_createdByUserId_fkey`;

-- DropForeignKey
ALTER TABLE `post_analytics_daily_snapshot` DROP FOREIGN KEY `post_analytics_daily_snapshot_brandId_fkey`;

-- DropForeignKey
ALTER TABLE `post_analytics_daily_snapshot` DROP FOREIGN KEY `post_analytics_daily_snapshot_postId_fkey`;

-- DropIndex
DROP INDEX `approval_workflows_livestreamId_fkey` ON `approval_workflows`;

-- AlterTable
ALTER TABLE `PlatformLimit` MODIFY `platform` ENUM('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'TWITTER_X', 'PINTEREST', 'YOUTUBE', 'TWITCH', 'THREADS', 'BLUESKY', 'REDDIT', 'GOOGLE_BUSINESS', 'TELEGRAM', 'GOOGLE_DRIVE') NOT NULL;

-- AlterTable
ALTER TABLE `approval_workflows` DROP COLUMN `livestreamId`;

-- AlterTable
ALTER TABLE `best_time_slots` MODIFY `platform` ENUM('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'TWITTER_X', 'PINTEREST', 'YOUTUBE', 'TWITCH', 'THREADS', 'BLUESKY', 'REDDIT', 'GOOGLE_BUSINESS', 'TELEGRAM', 'GOOGLE_DRIVE') NOT NULL;

-- AlterTable
ALTER TABLE `bluesky_accounts` ADD COLUMN `emailConfirmed` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `competitor_analysis` MODIFY `platform` ENUM('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'TWITTER_X', 'PINTEREST', 'YOUTUBE', 'TWITCH', 'THREADS', 'BLUESKY', 'REDDIT', 'GOOGLE_BUSINESS', 'TELEGRAM', 'GOOGLE_DRIVE') NOT NULL;

-- AlterTable
ALTER TABLE `hashtag_trackers` MODIFY `platform` ENUM('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'TWITTER_X', 'PINTEREST', 'YOUTUBE', 'TWITCH', 'THREADS', 'BLUESKY', 'REDDIT', 'GOOGLE_BUSINESS', 'TELEGRAM', 'GOOGLE_DRIVE') NOT NULL;

-- AlterTable
ALTER TABLE `inbox_items` MODIFY `platform` ENUM('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'TWITTER_X', 'PINTEREST', 'YOUTUBE', 'TWITCH', 'THREADS', 'BLUESKY', 'REDDIT', 'GOOGLE_BUSINESS', 'TELEGRAM', 'GOOGLE_DRIVE') NOT NULL;

-- AlterTable
ALTER TABLE `link_items` ADD COLUMN `isAutoGenerated` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `social_accounts` MODIFY `platform` ENUM('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'TWITTER_X', 'PINTEREST', 'YOUTUBE', 'TWITCH', 'THREADS', 'BLUESKY', 'REDDIT', 'GOOGLE_BUSINESS', 'TELEGRAM', 'GOOGLE_DRIVE') NOT NULL;

-- AlterTable
ALTER TABLE `tracked_videos` MODIFY `platform` ENUM('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'TWITTER_X', 'PINTEREST', 'YOUTUBE', 'TWITCH', 'THREADS', 'BLUESKY', 'REDDIT', 'GOOGLE_BUSINESS', 'TELEGRAM', 'GOOGLE_DRIVE') NOT NULL DEFAULT 'YOUTUBE';

-- AlterTable
ALTER TABLE `youtube_channels` DROP COLUMN `supportsLivestream`;

-- DropTable
DROP TABLE `livestream_highlights`;

-- DropTable
DROP TABLE `livestreams`;

-- DropTable
DROP TABLE `post_analytics_daily_snapshot`;

-- CreateTable
CREATE TABLE `youtube_video_categories` (
    `id` VARCHAR(191) NOT NULL,
    `regionCode` VARCHAR(191) NOT NULL,
    `categoryId` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `youtube_video_categories_regionCode_idx`(`regionCode`),
    UNIQUE INDEX `youtube_video_categories_regionCode_categoryId_key`(`regionCode`, `categoryId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `youtube_playlist_cache` (
    `id` VARCHAR(191) NOT NULL,
    `brandId` VARCHAR(191) NOT NULL,
    `playlistId` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `description` TEXT NULL,
    `itemCount` INTEGER NOT NULL DEFAULT 0,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `youtube_playlist_cache_brandId_idx`(`brandId`),
    UNIQUE INDEX `youtube_playlist_cache_brandId_playlistId_key`(`brandId`, `playlistId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `youtube_subscriptions` (
    `id` VARCHAR(191) NOT NULL,
    `youtube_channel_id` VARCHAR(191) NOT NULL,
    `channel_id` VARCHAR(191) NOT NULL,
    `topic_url` VARCHAR(191) NOT NULL,
    `hub_secret` VARCHAR(191) NOT NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
    `lease_seconds` INTEGER NOT NULL DEFAULT 864000,
    `subscribed_at` DATETIME(3) NULL,
    `expires_at` DATETIME(3) NULL,
    `last_event_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `youtube_subscriptions_youtube_channel_id_key`(`youtube_channel_id`),
    INDEX `youtube_subscriptions_channel_id_idx`(`channel_id`),
    INDEX `youtube_subscriptions_status_expires_at_idx`(`status`, `expires_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `post_network_overrides` (
    `id` VARCHAR(191) NOT NULL,
    `postId` VARCHAR(191) NOT NULL,
    `platform` ENUM('INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'TWITTER_X', 'PINTEREST', 'YOUTUBE', 'TWITCH', 'THREADS', 'BLUESKY', 'REDDIT', 'GOOGLE_BUSINESS', 'TELEGRAM', 'GOOGLE_DRIVE') NOT NULL,
    `useTemplate` BOOLEAN NOT NULL DEFAULT true,
    `caption` TEXT NULL,
    `mediaUrls` TEXT NULL,
    `threadPosts` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `post_network_overrides_postId_platform_key`(`postId`, `platform`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `youtube_playlist_cache` ADD CONSTRAINT `youtube_playlist_cache_brandId_fkey` FOREIGN KEY (`brandId`) REFERENCES `brands`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `youtube_subscriptions` ADD CONSTRAINT `youtube_subscriptions_youtube_channel_id_fkey` FOREIGN KEY (`youtube_channel_id`) REFERENCES `youtube_channels`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `post_network_overrides` ADD CONSTRAINT `post_network_overrides_postId_fkey` FOREIGN KEY (`postId`) REFERENCES `posts`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
